# battle_config.py

# Trump相关参数
TRUMP_BASE_HEALTH = 100
TRUMP_HEALTH_PER_LEVEL_INCREASE = 50
TRUMP_BASE_MOVE_SPEED = 50
TRUMP_SLOW_DOWN_RATE = 0.05
TRUMP_MIN_MOVE_SPEED = 10
TRUMP_ATTACK_DAMAGE = 5
TRUMP_ATTACK_INTERVAL = 1.0

# Meme攻击相关参数
MEME_ATTACK_INTERVAL = 2.0
MEME_BASE_DAMAGE = 1
MEME_PROJECTILE_SPEED = 150
MEME_BASE_HEALTH = 20
MEME_HEALTH_PER_STAR = 10

# 星级对应的伤害系数
STAR_DAMAGE_COEFFICIENTS = {
    1: 1.0,
    2: 1.2,
    3: 1.5,
    4: 2.0,
    5: 2.5
}

# 其他游戏平衡参数
MAX_SLOW_DOWN_EFFECT = 0.75
PROJECTILE_SIZE = (20, 20)

# 从config.py导入的常量
WHITE_HOUSE_CELL_INDEX = -1 